name: Closit
options:
  bundleIdPrefix: com.closeit
  deploymentTarget:
    macOS: "14.0"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    majorVersion: 2.6.4

targets:
  Closit:
    type: application
    platform: macOS
    sources:
      - Closit
    dependencies:
      - package: Sparkle
    settings:
      base:
        INFOPLIST_KEY_LSUIElement: YES
        SWIFT_VERSION: "5.0"
        DEVELOPMENT_TEAM: "X34323ZGU9"
        PRODUCT_BUNDLE_IDENTIFIER: com.closeit.closit
        PRODUCT_NAME: Closit
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0.38"
        CURRENT_PROJECT_VERSION: "38"
        INFOPLIST_FILE: "Closit/Info.plist"
        ENABLE_HARDENED_RUNTIME: YES
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: ${APPLE_CERT_HASH}
          PROVISIONING_PROFILE_SPECIFIER: ${PROFILE_UUID}
          OTHER_CODE_SIGN_FLAGS: "--timestamp"
          CODE_SIGN_ENTITLEMENTS: Closit/Closit.entitlements
  ClositTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - ClositTests
    dependencies:
      - target: Closit
    settings:
      base:
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ${APPLE_TEAM_ID}
        GENERATE_INFOPLIST_FILE: YES
